require('core/options')
require('core/commands')
require('core/colors')

require('plugins')
require('plugins/airline')
require('plugins/commentary')
require('plugins/ctrlsf')
require('plugins/fzf')
require('plugins/gh-line')
require('plugins/nerdtree')
require('plugins/vim-rest-console')

require('plugins/nvim-lspconfig')
require('plugins/nvim-lspconfig-format')
require('plugins/nvim-cmp')
require('plugins/nvim-treesitter')
